### ISSUE TITLE
รายงานบัค : *บัคตกแมพ*

### ISSUE THREAD

**Issue by RedinaldSF** [aktah/samp-f4u-issues#3]
**อธิบายข้อผิดพลาด**
บัคตกแมพ

**ทำซ้ำ**
ขั้นตอนในการทำให้เกิดข้อผิดพลาดนั้น:
1. เวลาที่กดเดินหน้าหรือวิ่งไปที่ประตูวาร์ป
2. กดต่อยไปที่ประตูพร้อมกับกำลังวิ่งอยู่
3. เดินทะลุประตู
4. ตกแมพ

**มันควรจะเป็นยังไง**
ไม่บัคตกแมพ (เหตุการณ์นี้เกิดขึ้นในบางครั้ง)

**ภาพประกอบ**
---------------

**อื่น ๆ**
----------------

**Comment by aktah** [comment]
ไม่ได้เป็นทุกที่ใช่ไหมครับ อารมณ์เหมือนวาร์ปไปแล้วแมฟโหลดไม่ทัน เดินทะลุ Object ประตูจนตกแมฟ

**Comment by RedinaldSF** [comment]
ใช่ครับ
จะเป็นบางที่และจะมีโอกาสเป็นมากขึ้นถ้ากดเดินหน้าหรือวิ่งแล้วต่อยไปที่ประตู

ในวันที่ อา. 19 ม.ค. 2020 15:58 aktah <notifications@github.com> เขียนว่า:
