### ISSUE TITLE
รายงานบั๊ก : จักรยานเช่า

### ISSUE THREAD

**Issue by RedinaldSF** [aktah/samp-f4u-issues#4]
**อธิบายข้อผิดพลาด**
เวลาที่เกิดตรงจุดเกิดของ new player จะมีจักรยานเช่าให้เช่าแต่หากว่าขึ้นไปนั่งแล้วพิมพ์ /ph /party หรือ /gps จะทำให้ปุ่ม controller เด้งขึ้นมาและสามารถใช้งานจักรยานเช่าได้แบบไม่ต้องเสียเงินซื้อหรือ /buy เลย

**ทำซ้ำ**
ขั้นตอนในการทำให้เกิดข้อผิดพลาดนั้น:
1. ขึ้นไปบนจักรยานเช่า
2. พิมพ์ /ph , /party , /gps
3. กดกลับ
4. ปุ่ม controller เด้งขึ้นมาและสามารถใช้งานได้ฟรี

**มันควรจะเป็นยังไง**
คำอธิบายที่ชัดเจนและรัดกุมในสิ่งที่คุณคาดให้มันเกิดขึ้น

**ภาพประกอบ**
-------------

**อื่น ๆ**
--------------

**Comment by aktah** [comment]
เท่าที่ทดสอบกับ APK ตัวปัจจุบันยังไม่พบปัญหานี้เลยครับ งั้นรอเปิดเซิร์ฟเวอร์ถ้าพบเห็นก็แจ้งมาใหม่นะครับ
