### ISSUE TITLE
[ฟีเจอร์] เพิ่มงาน.

### ISSUE THREAD

**Issue by WusleyCrown** [aktah/samp-f4u-issues#6]
1อยากให้ทาง Admin เพิ่มงานสักหน่อยสัก 1-2 งานทางผู้เล่นจะได้มีอะไรทำกัน - ไม่เบื่อ 
2. อยากให้ทาง Admin ช่วยปรับดาเมจให้ Android ถ้าทำได้. เพราะไม่สามารถสุ้ PC ได้.
3 อยากให้ทาง Admin เพิ่ม /sc 3 หรือ เวลาเราออกเกมมันจะได้อยุ่ล่าสุด.

**Comment by aktah** [comment]
เพิ่มอาชีพก็ส่วนอาชีพเหมือนแนะนำฟีเจอร์หลาย ๆ อย่างรวมกัน

อาชีพที่ต้องการให้เพิ่มคืออะไร มีขั้นตอนการทำอย่างไรบ้าง? การเสนอพวกนี้คุณต้องเขียนตั้งแต่ต้นจนจบโปรเซสงานเลยว่ามีอะไรเกิดขึ้นบ้าง เหมือนยกภาระทั้งหมดให้ผู้ดูแล ดังนั้นอะไรที่ช่วยได้ก็รบกวนหน่อยนะครับ (ถ้าเบื่อกันตั้งแต่ตอนนี้ก็ยังไม่ควรเล่น ควรรอระบบมาครบก่อน เพราะอะไรหลาย ๆ อย่างยังไม่ทำเลย)
